Repository Angelo1720/futbol_Interior, pull requests merged in 2024-06, with the labels that each got.

#18 [Ediciones] listado
  app/Http/Controllers/EdicionController.php
  app/Models/Edicion.php
  database/migrations/2024_05_23_021503_create_edicion_table.php
  resources/scss/ediciones/index.scss
  resources/scss/main.scss
  resources/views/campeonatos/index.blade.php
  resources/views/ediciones/index.blade.php
  resources/views/equipos/edit.blade.php
  routes/web.php
Labels: test

#17 [altaPartidos] alta básica funcionando, con alineaciones y suplentes
  app/Enum/Posiciones.php
  app/Http/Controllers/CampeonatoController.php
  app/Http/Controllers/ControladorUsuario.php
  app/Http/Controllers/EdicionController.php
  app/Http/Controllers/EquipoController.php
  app/Http/Controllers/PartidoController.php
  app/Models/Edicion.php
  app/Models/Edicion_Equipo.php
  app/Models/Equipo.php
  app/Models/Jugador.php
  app/Models/Partido.php
  database/migrations/2024_05_28_183439_create_table_partidos.php
  database/migrations/2024_05_28_210019_create_table_jugadores.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EdicionesTableSeeder.php
  database/seeders/JugadoresTableSeeder.php
  resources/js/app.js
  resources/js/dashboard.js
  resources/views/ediciones/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partidos/create.blade.php
  routes/web.php
Labels: test

#21 [inicioInvitado] Inicio invitado
  app/Http/Controllers/ControladorUsuario.php
  app/Providers/RouteServiceProvider.php
  public/Images/iniciar-sesion.png
  public/Images/loginFutbolUruguayo.jpeg
  public/Images/registro.png
  resources/scss/app.scss
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/usuarios/create.blade.php
  routes/web.php
Labels: test

#20 [fixVarios] fix generales
  lang/es/validation.php
  resources/js/app.js
  resources/js/equipo.js
  resources/js/partido.js
  resources/js/register.js
  resources/views/campeonatos/create.blade.php
  resources/views/campeonatos/edit.blade.php
  resources/views/campeonatos/index.blade.php
  resources/views/ediciones/create.blade.php
  resources/views/ediciones/index.blade.php
  resources/views/equipos/create.blade.php
  resources/views/equipos/edit.blade.php
  resources/views/equipos/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/partidos/create.blade.php
  resources/views/usuarios/create.blade.php
  resources/views/usuarios/edit.blade.php
  resources/views/usuarios/index.blade.php
Labels: test

#24 [equiposInvitado] Equipos invitado
  app/Http/Controllers/EquipoController.php
  app/Providers/AppServiceProvider.php
  lang/es/pagination.php
  public/Images/campo.png
  public/Images/escudo.png
  public/Images/menu.png
  public/Images/premio-de-futbol.png
  resources/scss/Equipos/listadoEquipos.scss
  resources/scss/main.scss
  resources/views/equipos/listadoEquipos.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/vendor/pagination/bootstrap-5.blade.php
  resources/views/vendor/pagination/default.blade.php
  routes/web.php
Labels: falta contenido

#26 [campeonatosInvitado]
  app/Http/Controllers/CampeonatoController.php
  public/Images/portadaCampeonatos.jpg
  resources/scss/campeonatos/listadoCampeonatos.scss
  resources/scss/main.scss
  resources/views/campeonatos/campeonatosDivA.blade.php
  resources/views/campeonatos/campeonatosDivB.blade.php
  resources/views/campeonatos/campeonatosDivC.blade.php
  resources/views/campeonatos/listadoCampeonatos.blade.php
  resources/views/equipos/listadoEquipos.blade.php
  resources/views/layouts/navigation.blade.php
  routes/web.php
Labels: test

#28 [administrarJugadores] abm jugadores por club
  app/Http/Controllers/JugadorController.php
  app/Models/Jugador.php
  database/migrations/2024_05_28_210019_create_table_jugadores.php
  database/seeders/JugadoresTableSeeder.php
  lang/es/validation.php
  resources/scss/Jugadores/index.scss
  resources/scss/main.scss
  resources/views/equipos/index.blade.php
  resources/views/jugadores/create.blade.php
  resources/views/jugadores/edit.blade.php
  resources/views/jugadores/index.blade.php
  routes/web.php
Labels: test

#29 [completarAdminEdicion] funcionalidad para test, error css en select2
  app/Http/Controllers/EdicionController.php
  app/Http/Controllers/PartidoController.php
  app/Models/Equipo.php
  resources/js/app.js
  resources/js/edicion.js
  resources/scss/ediciones/edit.scss
  resources/views/ediciones/edit.blade.php
  resources/views/ediciones/editInfo.blade.php
  routes/web.php
Labels: test, falta contenido

#31 [agregarTitulos] añadido de titulos y mini cambio css en perfil
  resources/views/campeonatos/create.blade.php
  resources/views/campeonatos/edit.blade.php
  resources/views/campeonatos/index.blade.php
  resources/views/ediciones/create.blade.php
  resources/views/ediciones/edit.blade.php
  resources/views/ediciones/editInfo.blade.php
  resources/views/ediciones/index.blade.php
  resources/views/equipos/create.blade.php
  resources/views/equipos/edit.blade.php
  resources/views/equipos/index.blade.php
  resources/views/jugadores/create.blade.php
  resources/views/jugadores/edit.blade.php
  resources/views/jugadores/index.blade.php
  resources/views/jugadores_historicos/create.blade.php
  resources/views/jugadores_historicos/edit.blade.php
  resources/views/jugadores_historicos/index.blade.php
  resources/views/partidos/create.blade.php
  resources/views/profile/edit.blade.php
  resources/views/usuarios/create.blade.php
  resources/views/usuarios/edit.blade.php
  resources/views/usuarios/index.blade.php
Labels: test

#33 [fixesGenerales] fixes generales, separados por commit
  app/Http/Controllers/CampeonatoController.php
  app/Http/Controllers/ControladorUsuario.php
  app/Http/Controllers/EquipoController.php
  app/Http/Controllers/JugadorController.php
  app/Http/Controllers/JugadorHistoricoController.php
  public/Images/colita-merentiel.png
  resources/scss/Equipos/index.scss
  resources/scss/campeonatos/index.scss
  resources/scss/ediciones/index.scss
  resources/scss/jugadores_historicos/index.scss
  resources/scss/main.scss
  resources/scss/usuarios/index.scss
  resources/views/campeonatos/index.blade.php
  resources/views/campeonatos/listadoCampeonatos.blade.php
  resources/views/ediciones/index.blade.php
  resources/views/equipos/index.blade.php
  resources/views/jugadores/index.blade.php
  resources/views/jugadores_historicos/index.blade.php
  resources/views/usuarios/index.blade.php
Labels: falta contenido
