Repository Angelo1720/futbol_Interior, pull requests merged in 2024-07, with the labels that each got.

#36 [buscadorEnVistaGuest] buscador en cada vista guest
  app/Http/Controllers/CampeonatoController.php
  app/Http/Controllers/EquipoController.php
  app/Http/Controllers/JugadorHistoricoController.php
  resources/views/campeonatos/campeonatosDivA.blade.php
  resources/views/campeonatos/campeonatosDivB.blade.php
  resources/views/campeonatos/campeonatosDivC.blade.php
  resources/views/campeonatos/listadoCampeonatos.blade.php
  resources/views/equipos/listadoEquipos.blade.php
  resources/views/jugadores_historicos/listadoHistoricos.blade.php
Labels: test

#37 [fixQuerysDataTables] fix en controladores
  app/Http/Controllers/CampeonatoController.php
  app/Http/Controllers/ControladorUsuario.php
  app/Http/Controllers/EdicionController.php
  app/Http/Controllers/EquipoController.php
  app/Http/Controllers/JugadorController.php
  app/Http/Controllers/JugadorHistoricoController.php
Labels: test

#39 [apiListadoCampeonatos] listado
  app/Http/Controllers/CampeonatoController.php
  routes/api.php
Labels: test, falta contenido

#41 [guiaInstalacion] guiaInstalacion - seeders
  database/seeders/CampeonatosTableSeeder.php
  database/seeders/EdicionesTableSeeder.php
  database/seeders/EquiposTableSeeder.php
  database/seeders/JugadoresHistoricosSeeder.php
  database/seeders/JugadoresTableSeeder.php
  guia_instalacion.txt
  public/Images/Guaviyu.png
  public/Images/alzugaray.png
  public/Images/alzugaray.webp
  public/Images/juan-fleitas.png
  resources/scss/dashboard.scss
  resources/views/dashboard.blade.php
  resources/views/ediciones/edit.blade.php
Labels: falta contenido

#38 [listadoHistoricosApi] endpoint pronto
  app/Http/Controllers/JugadorHistoricoController.php
  routes/api.php
Labels: test
